### ISSUE TITLE
Indistinguishable Callback Executions

### ISSUE THREAD

**Issue by twittwer** [thenativeweb/json-lines-client#1]
### Situation:
When I call the client method my callback registers listeners for data, end, error on the stream.
In case of an error I will try to reconnect.
```
client( {...}, server => {
  server.stream.on( 'data', data => {
    // ...
  } );
  server.stream.on( 'error', () => {
    reconnect();
  } );
  server.stream.on( 'end', () => {
    // ...
  } );
  // used somewhere else: server.disconnect()
} );
```
### Problem
If an error occurs the json-lines module (client) is emitting an error event on the stream as expected, but also executes the callback again. That way the error handlers are registered twice and two reconnect attempts will be initiated.
In your code I saw, that the second callback execution drains the function body of server's disconnect method. - I don't understand why this is needed, when the original disconnect method is already checking, if there's an existing request/response object.
In the meanwhile I tried to differentiate the two callback executions, but beside disconnect's function body they are equal and the I wasn't able to make a decision based on that.

### Question
Could you explain me why the callback ist executed twice without any error indicator?
Could you give advice how to prevent the duplicated reconnect without a lock variable (my current solution)?

Thank you in advance 🙂

**Comment by goloroden** [comment]
Sorry for never having replied to your question here. We won't continue development and maintenance of this module, hence I'm going to close this.
